[project]
site_name = "twitch.py"
site_description = "Real-time Twitch Event Handling and Helix API Integration in Python."
site_author = "mrsnifo"
site_url = "https://twitchpy.readthedocs.io"
repo_url = "https://github.com/mrsnifo/twitch.py"
copyright = "Copyright &copy; 2026-present mrsnifo"
docs_dir = "src"
site_dir = "site"
use_directory_urls = true

nav = [
    { "Getting started" = [
        "index.md",
        { "Concepts" = "concepts.md" },
        { "Quickstart" = "quickstart.md" },
        { "Logging" = "logging.md" }
    ]},
    { "Reference" = [
        { "App" = "reference/app/app.md" },
        { "Classes" = "reference/app/classes.md" },
        { "Errors" = "reference/app/errors.md" },
        { "Models" = "reference/app/models.md" },
        { "Utils" = "reference/app/utils.md" }
    ]},
    { "Eventsub" = [
        { "Index" = "reference/eventsub/index.md" },
        { "Client" = "reference/eventsub/client.md" },
        { "Classes" = "reference/eventsub/classes.md" },
        { "Models" = "reference/eventsub/models.md" },
        { "Errors" = "reference/eventsub/errors.md" },
        { "Debug" = "reference/eventsub/debug.md" }
    ]},
    { "OAuth" = [
        { "Flows" = "reference/oauth/flows.md" },
        { "Scopes" = "reference/oauth/scopes.md" },
        { "Models" = "reference/oauth/models.md" }
    ]},
    { "Extensions" = [
        { "Tasks" = "ext/tasks.md" }
    ]}
]

[project.theme]
custom_dir = "overrides"
language = "en"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
primary = "deep purple"
accent = "deep purple"
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
primary = "deep purple"
accent = "deep purple"
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
primary = "deep purple"
accent = "deep purple"
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"


[project.theme.icon]
logo = "lucide/book-open-text"
repo = "lucide/github"


[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/mrsnifo"


[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/sofienhichri"


[project.extra.analytics]
provider = "google"
property = "G-Q0MYXS1EXK"


[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["..", "twitch"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "numpy"
inherited_members = true
show_source = false
show_root_heading = true
